#!/usr/bin/env python

import sys
import random

import networkx as nx

G = nx.DiGraph()


nodes = [i for i in range(1, random.randint(10, 20))]
G.add_nodes_from(nodes)

num_edges = len(nodes) - random.randint(0, 5)
edges = set([])

while len(edges) != num_edges:
    i = random.randint(1, len(nodes) - 1)
    j = random.randint(i + 1, len(nodes))
    edges.add((i, j))

G.add_nodes_from(nodes)
G.add_edges_from(edges)

with open(f"data/test{sys.argv[1]}", "w") as f:
    f.write(f"{len(nodes)} {len(edges)}\n")
    for edge in edges:
        f.write(f"{edge[0]} {edge[1]}\n")

with open(f"data/ans{sys.argv[1]}", "w") as f:
    longest_path = nx.dag_longest_path(G)
    f.write(f"{len(longest_path) - 1}\n")

